import React, { useState, useRef, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { motion, AnimatePresence } from 'motion/react';
import { Bot, X, Send, Sparkles, MessageSquare, Calculator, Zap, Palette, Download, Share2, ImageIcon } from 'lucide-react';
import { askPixoAI } from '../services/aiService';

export default function PixoAI() {
  const { t } = useTranslation();
  const [isOpen, setIsOpen] = useState(false);
  const [input, setInput] = useState('');
  const [messages, setMessages] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages]);

  const handleSend = async (e?: React.FormEvent, customPrompt?: string) => {
    if (e) e.preventDefault();
    const text = customPrompt || input;
    if (!text.trim() || loading) return;

    const userMsg = { role: 'user', content: text };
    setMessages(prev => [...prev, userMsg]);
    setInput('');
    setLoading(true);

    const response = await askPixoAI(text);
    const aiMsg = { 
      role: 'assistant', 
      content: response.content, 
      type: response.type,
      imageUrl: (response as any).imageUrl 
    };
    setMessages(prev => [...prev, aiMsg]);
    setLoading(false);
  };

  const services = [
    { id: 'gen', icon: <ImageIcon className="w-4 h-4" />, label: 'Generate Design concept', prompt: 'Generate a futuristic glass villa concept in the middle of a forest at sunset.' },
    { id: 'estimate', icon: <Calculator className="w-4 h-4" />, label: t('ai_service_estimate'), prompt: 'Can you provide a rough estimate and timeline for a luxury residential villa render?' },
    { id: 'trends', icon: <Zap className="w-4 h-4" />, label: t('ai_service_trends'), prompt: 'What are the current top 3 design trends in architectural visualization?' },
  ];

  const handleDownload = async (url: string) => {
    try {
      const response = await fetch(url);
      const blob = await response.blob();
      const blobUrl = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = blobUrl;
      link.download = `pixo-ai-${Date.now()}.jpg`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(blobUrl);
    } catch (error) {
      console.error('Download failed:', error);
      // Fallback: just open in new tab if fetch fails due to CORS (though pollination.ai usually allows it)
      window.open(url, '_blank');
    }
  };

  const handleShare = async (url: string) => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Pixo AI Architectural Concept',
          text: 'Check out this design generated by Pixo AI!',
          url: url
        });
      } catch (err) {
        console.error(err);
      }
    } else {
        navigator.clipboard.writeText(url);
        alert('Image link copied to clipboard!');
    }
  };

  return (
    <div className="fixed bottom-8 right-8 z-[100]">
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ opacity: 0, y: 50, scale: 0.9, filter: 'blur(10px)' }}
            animate={{ opacity: 1, y: 0, scale: 1, filter: 'blur(0px)' }}
            exit={{ opacity: 0, y: 50, scale: 0.9, filter: 'blur(10px)' }}
            className="absolute bottom-20 right-0 w-[400px] max-w-[90vw] h-[600px] glass-card flex flex-col overflow-hidden shadow-2xl !border-[var(--glass-border)] shadow-brand-accent/5 backdrop-blur-2xl"
          >
            {/* Header */}
            <div className="bg-brand-accent/10 p-6 flex items-center justify-between border-b border-[var(--glass-border)]">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-full bg-brand-accent flex items-center justify-center text-black">
                  <Bot className="w-6 h-6" />
                </div>
                <div>
                  <h4 className="text-primary font-bold leading-none">{t('ai_assistant_name')}</h4>
                  <p className="text-[10px] text-brand-accent uppercase tracking-widest mt-1 font-bold">{t('ai_assistant_tagline')}</p>
                </div>
              </div>
              <button 
                onClick={() => setIsOpen(false)}
                className="text-primary/40 hover:text-primary transition-colors"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Messages */}
            <div 
              ref={scrollRef}
              className="flex-grow overflow-y-auto p-6 space-y-6 scrollbar-thin scrollbar-thumb-brand-accent/20"
            >
              {messages.length === 0 && (
                <div className="text-center py-10 space-y-4">
                  <div className="w-16 h-16 rounded-full bg-brand-accent/10 flex items-center justify-center mx-auto text-brand-accent">
                    <Sparkles className="w-8 h-8" />
                  </div>
                  <p className="text-primary font-light px-6 italic opacity-80">{t('ai_welcome')}</p>
                  
                  <div className="grid grid-cols-1 gap-2 px-4 mt-8">
                    {services.map(s => (
                      <button
                        key={s.id}
                        onClick={() => handleSend(undefined, s.prompt)}
                        className="flex items-center gap-3 p-4 rounded-xl bg-[var(--glass-bg)] border border-[var(--glass-border)] text-left hover:border-brand-accent transition-all group"
                      >
                        <div className="text-brand-accent group-hover:scale-110 transition-transform">{s.icon}</div>
                        <span className="text-xs text-primary/70 font-medium">{s.label}</span>
                      </button>
                    ))}
                  </div>
                </div>
              )}

              {messages.map((msg, i) => (
                <motion.div
                  key={i}
                  initial={{ opacity: 0, x: msg.role === 'user' ? 20 : -20 }}
                  animate={{ opacity: 1, x: 0 }}
                  className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}
                >
                  <div className={`${
                    msg.role === 'user' 
                      ? 'bg-brand-accent text-black rounded-2xl rounded-tr-none' 
                      : 'bg-[var(--glass-bg)] text-primary border border-[var(--glass-border)] rounded-2xl rounded-tl-none'
                    } p-4 max-w-[85%] text-sm leading-relaxed shadow-lg`}
                  >
                    {msg.content}
                    
                    {msg.type === 'image' && msg.imageUrl && (
                      <div className="mt-4 space-y-4">
                        <div className="relative aspect-square rounded-xl overflow-hidden border border-white/10 group">
                           <img 
                            src={msg.imageUrl} 
                            alt="AI Concept" 
                            className="w-full h-full object-cover"
                            referrerPolicy="no-referrer"
                           />
                           <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center gap-4">
                              <button 
                                onClick={() => handleDownload(msg.imageUrl)}
                                className="w-10 h-10 rounded-full bg-white text-black flex items-center justify-center hover:scale-110 transition-transform"
                              >
                                <Download className="w-4 h-4" />
                              </button>
                              <button 
                                onClick={() => handleShare(msg.imageUrl)}
                                className="w-10 h-10 rounded-full bg-white text-black flex items-center justify-center hover:scale-110 transition-transform"
                              >
                                <Share2 className="w-4 h-4" />
                              </button>
                           </div>
                        </div>
                        <div className="flex gap-2">
                           <button 
                             onClick={() => handleDownload(msg.imageUrl)}
                             className="flex-grow py-2 bg-white/10 hover:bg-white/20 rounded-lg text-[10px] font-bold uppercase tracking-widest transition-colors flex items-center justify-center gap-2"
                           >
                              <Download className="w-3 h-3" /> {t('download')}
                           </button>
                           <button 
                             onClick={() => handleShare(msg.imageUrl)}
                             className="px-4 py-2 bg-white/10 hover:bg-white/20 rounded-lg transition-colors"
                           >
                              <Share2 className="w-3 h-3" />
                           </button>
                        </div>
                      </div>
                    )}
                  </div>
                </motion.div>
              ))}

              {loading && (
                <div className="flex justify-start">
                  <div className="bg-[var(--glass-bg)] text-primary/40 border border-[var(--glass-border)] rounded-2xl p-4 flex items-center gap-3 text-xs italic">
                    <Zap className="w-3 h-3 animate-pulse text-brand-accent" />
                    {t('ai_thinking')}
                  </div>
                </div>
              )}
            </div>

            {/* Input */}
            <form onSubmit={handleSend} className="p-6 bg-black/20 border-t border-[var(--glass-border)]">
              <div className="relative">
                <input 
                  type="text" 
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  placeholder={t('ask_ai_placeholder')}
                  className="w-full bg-[var(--input-bg)] border-[var(--glass-border)] rounded-2xl py-4 pl-6 pr-14 text-sm text-primary placeholder:text-primary/20 outline-none focus:border-brand-accent/50 transition-colors"
                />
                <button 
                  type="submit"
                  disabled={loading}
                  className="absolute right-2 top-1/2 -translate-y-1/2 w-10 h-10 rounded-xl bg-brand-accent text-black flex items-center justify-center hover:scale-105 transition-transform disabled:opacity-50"
                >
                  <Send className="w-4 h-4" />
                </button>
              </div>
            </form>
          </motion.div>
        )}
      </AnimatePresence>

      <button
        onClick={() => setIsOpen(!isOpen)}
        className="w-16 h-16 rounded-full bg-brand-accent text-black flex items-center justify-center shadow-2xl shadow-brand-accent/30 hover:scale-110 active:scale-95 transition-all group relative"
      >
        <AnimatePresence mode="wait">
          {isOpen ? (
            <motion.div 
              key="close"
              initial={{ rotate: -90, opacity: 0 }}
              animate={{ rotate: 0, opacity: 1 }}
              exit={{ rotate: 90, opacity: 0 }}
            >
              <X className="w-7 h-7" />
            </motion.div>
          ) : (
            <motion.div 
              key="open"
              initial={{ rotate: 90, opacity: 0 }}
              animate={{ rotate: 0, opacity: 1 }}
              exit={{ rotate: -90, opacity: 0 }}
            >
              <MessageSquare className="w-7 h-7" />
            </motion.div>
          )}
        </AnimatePresence>
        
        {!isOpen && (
          <span className="absolute -top-1 -right-1 w-5 h-5 bg-white rounded-full flex items-center justify-center text-[10px] font-bold text-black border-2 border-brand-primary">
            1
          </span>
        )}
      </button>
    </div>
  );
}
